CREATE SEQUENCE resource_id_seq;
CREATE EXTENSION cube;
CREATE EXTENSION earthdistance;

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  place_id VARCHAR(255),
  latitude DECIMAL(9, 6),
  longitude DECIMAL(9, 6),
  role VARCHAR(50) DEFAULT 'user' CHECK (role IN ('user', 'moderator', 'admin')),
  profile JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE resources (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  alt_name VARCHAR(255),
  categories JSONB NOT NULL,
  services JSONB,
  resource_type VARCHAR(50),
  url VARCHAR(255),
  image_url TEXT,
  location_name VARCHAR(255) NOT NULL,
  address1 VARCHAR(255),
  address2 VARCHAR(255),
  city VARCHAR(255),
  county VARCHAR(255),
  state VARCHAR(255),
  postal_code VARCHAR(255),
  coverage_area VARCHAR(255),
  description TEXT NOT NULL,
  tips TEXT,
  application_process TEXT,
  documents_required TEXT,
  phone_numbers JSONB,
  vacancies INT DEFAULT NULL,
  capacity INT DEFAULT NULL,
  wait_list INT DEFAULT NULL,
  wait_time VARCHAR(50),
  hours JSONB,
  hours_text TEXT,
  rating DECIMAL(2, 1) DEFAULT 0.0,
  user_id INT REFERENCES users(id),
  owner_id INT REFERENCES users(id),
  last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_moderator_id INT REFERENCES users(id),
  moderator_ids JSONB,
  last_verified TIMESTAMP,
  verification_source VARCHAR(100),
  transportation_options JSONB,
  place_id VARCHAR(255),
  latitude DECIMAL(9, 6),
  longitude DECIMAL(9, 6),
  service_fees BOOLEAN,
  payment_notes TEXT,
  eligibility JSONB,
  eligibility_notes TEXT,
  special_eligibility JSONB,
  special_eligibility_notes TEXT,
  languages TEXT,
  housing_type VARCHAR(50),
  wheelchair_access VARCHAR(255),
  accessibility_features JSONB,
  crisis_services VARCHAR(255),
  walk_in_services VARCHAR(255),
  appointment_required VARCHAR(255),
  contact_info JSONB,
  recommendation_matrix JSONB,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_resources_location ON resources USING GIST (ll_to_earth(latitude, longitude));

CREATE TABLE moderated_resources (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  alt_name VARCHAR(255),
  categories JSONB NOT NULL,
  services JSONB,
  resource_type VARCHAR(50),
  url VARCHAR(255),
  image_url TEXT,
  location_name VARCHAR(255) NOT NULL,
  address1 VARCHAR(255),
  address2 VARCHAR(255),
  city VARCHAR(255),
  county VARCHAR(255),
  state VARCHAR(255),
  postal_code VARCHAR(255),
  coverage_area VARCHAR(255),
  description TEXT NOT NULL,
  tips TEXT,
  application_process TEXT,
  documents_required TEXT,
  phone_numbers JSONB,
  vacancies INT DEFAULT NULL,
  capacity INT DEFAULT NULL,
  wait_list INT DEFAULT NULL,
  wait_time VARCHAR(50),
  hours JSONB,
  hours_text TEXT,
  rating DECIMAL(2, 1) DEFAULT 0.0,
  user_id INT REFERENCES users(id),
  owner_id INT REFERENCES users(id),
  last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_moderator_id INT REFERENCES users(id),
  moderator_ids JSONB,
  last_verified TIMESTAMP,
  verification_source VARCHAR(100),
  transportation_options JSONB,
  place_id VARCHAR(255),
  latitude DECIMAL(9, 6),
  longitude DECIMAL(9, 6),
  service_fees BOOLEAN,
  payment_notes TEXT,
  eligibility JSONB,
  eligibility_notes TEXT,
  special_eligibility JSONB,
  special_eligibility_notes TEXT,
  languages TEXT,
  housing_type VARCHAR(50),
  wheelchair_access VARCHAR(255),
  accessibility_features JSONB,
  crisis_services VARCHAR(255),
  walk_in_services VARCHAR(255),
  appointment_required VARCHAR(255),
  contact_info JSONB,
  recommendation_matrix JSONB,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE favorites (
  id BIGSERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id),
  resource_id INT REFERENCES resources(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, resource_id)
);
